import StyleDictionary, { type TransformedTokens } from 'style-dictionary';

type TokenValue = string | number | boolean | TokenObject | TokenValue[];

interface TokenObject {
  [key: string]: TokenValue;
}

// Recursively transform Style Dictionary token objects into TypeScript-friendly object
const tokensToObject = (tokens: TransformedTokens): TokenValue => {
  if ('value' in tokens) {
    return tokens.value;
  }
  if (typeof tokens === 'object') {
    const result: TokenObject = {};
    for (const [key, val] of Object.entries(tokens)) {
      result[key] = tokensToObject(val as TransformedTokens);
    }
    return result;
  }
  return tokens as TokenValue;
};

StyleDictionary.registerFormat({
  name: 'typescript/nested-objects',
  format: function ({ dictionary }) {
    const nested = tokensToObject(dictionary.tokens);

    return `/**
 * Do not edit directly
 * Generated by Style Dictionary
 */

export const tokens = ${JSON.stringify(nested, null, 2)} as const;

export type Tokens = typeof tokens;
`;
  },
});

const sd = new StyleDictionary('./src/theme/style-dictionary.config.jsonc');
sd.buildAllPlatforms();
